apiVersion: apps/v1
kind: Deployment
metadata:
  name: springapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springapp
  template:
    metadata:
      labels:
        app: springapp
    spec:
      containers:
        - name: springapp
          image: yeonheelee/springapp:latest
          ports:
            - containerPort: 8999

---
apiVersion: v1
kind: Service
metadata:
  name: springapp-service
spec:
  selector:
    app: springapp
  ports:
    - protocol: TCP
      port: 8999
      targetPort: 8999
  type: LoadBalancer